"""Shared constants for the Hermod window layer."""

BODY_CACHE_LIMIT = 8
PREFETCH_WARMUP_LIMIT = 4
SIDEBAR_MIN_WIDTH = 300
SIDEBAR_MAX_WIDTH = 300
MESSAGE_LIST_MIN_WIDTH = 320
MESSAGE_LIST_MAX_WIDTH = 680
MESSAGE_PAGE_STEP = 100
