"""Base mail-provider contract used during backend splitting."""

from typing import Protocol, runtime_checkable


@runtime_checkable
class MailProvider(Protocol):
    identity: str
    provider: str
    FOLDERS: list[tuple[str, str, str]]

    def fetch_messages(self, folder: str = 'inbox', limit: int = 50): ...
    def fetch_thread_messages(self, thread_id: str): ...
    def fetch_body(self, uid: str, folder: str | None = None): ...
    def fetch_attachment_data(self, uid: str, attachment: dict, folder: str | None = None): ...
    def mark_as_read(self, uid: str, folder: str | None = None): ...
    def mark_as_unread(self, uid: str, folder: str | None = None): ...
    def delete_message(self, uid: str, folder: str | None = None): ...
    def get_unread_count(self, folder: str = 'inbox'): ...
    def fetch_contacts(self, query: str = ''): ...
    def send_message(self, *args, **kwargs): ...
    def check_background_updates(self, tracked_folders=None, reconcile_counts=False): ...
    def update_cached_message_read_state(self, folder, uid, is_read): ...
    def remove_cached_message(self, folder, uid): ...
